runtime: custom
service: mtr-todos-233
env: flex
threadsafe: true
zones:
  - us-east1-b
  - us-east1-c
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
network:
  session_affinity: true
automatic_scaling:
  max_num_instances: 2
env_variables:
  ROOT_URL: http://127.0.0.1
  MONGO_URL: mongodb+srv://nullthefirst:8SuLZec23krnfQvS@cluster0-akhjz.gcp.mongodb.net/test?retryWrites=true&w=majority
  MAIL_URL:
skip_files:
  - ^(.*/)?\.dockerignore$
  - ^(.*/)?\yarn-error.log$
  - ^(.*/)?\.git$
  - ^(.*/)?\.hg$
  - ^(.*/)?\.svn$
